# Generated by Django 5.1.2 on 2024-11-25 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.IntegerField(choices=[(0, 'Not Liked'), (1, 'Liked')], default=0)),
                ('bookmarked', models.IntegerField(choices=[(0, 'Not Bookmarked'), (1, 'Bookmarked')], default=0)),
                ('unique_view', models.IntegerField(choices=[(0, 'Not Viewed'), (1, 'Viewed')], default=0)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
